"use client";

import { BarChart2, CalendarClock, IndianRupee, ListChecks, Plus, MessageSquare, Sparkles, UserPlus, ShieldAlert, Zap } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { AddWeddingFlowDialog } from "@/components/app-dashboard/dashboard/add-wedding-flow-dialog";
import { AiInsight } from "@/components/app-dashboard/dashboard/types";
import { Button, buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const variantStyles: Record<
  AiInsight["variant"],
  { Icon: React.ElementType; iconClass: string; bgClass: string }
> = {
  risk: { Icon: BarChart2, iconClass: "text-destructive", bgClass: "bg-destructive/15" },
  budget: { Icon: IndianRupee, iconClass: "text-emerald-400", bgClass: "bg-emerald-500/15" },
  vendor: { Icon: ShieldAlert, iconClass: "text-primary", bgClass: "bg-primary/15" },
  task: { Icon: ListChecks, iconClass: "text-amber-400", bgClass: "bg-amber-500/15" },
};

const EXTRA_INSIGHTS = [
  {
    id: "upcoming-events",
    Icon: CalendarClock,
    iconClass: "text-violet-400",
    bgClass: "bg-violet-500/15",
    title: "2 events in the next 7 days",
    description: "Ensure all vendors and tasks are confirmed",
    ctaLabel: "View calendar",
    ctaHref: "/app/tasks",
  },
];

type AiInsightsWidgetProps = {
  insights: AiInsight[];
  tasksHref?: string;
  messagesHref?: string;
  vendorsHref?: string;
};

export function AiInsightsWidget({
  insights,
  tasksHref = "/app/tasks",
  messagesHref = "/app/messages",
  vendorsHref = "/app/vendors",
}: AiInsightsWidgetProps) {
  const [addWeddingOpen, setAddWeddingOpen] = useState(false);

  return (
    <div className="flex h-full flex-col gap-4">
      {/* AI Insights */}
      <div className="flex min-h-0 flex-1 flex-col rounded-2xl border border-border/70 bg-card shadow-sm">
        <div className="flex shrink-0 items-center justify-between gap-3 border-b border-border/70 px-4 py-1.5 sm:px-5">
          <div className="flex items-center gap-2">
            <Sparkles className="size-3.5 text-primary" aria-hidden />
            <p className="text-sm font-semibold text-foreground">AI Insights</p>
            <span className="text-[11px] text-muted-foreground/60 italic">— Generated by  <span className="text-foreground not-italic font-medium">Hitched AI™</span></span>
          </div>
          <Link
            href="/app/tasks"
            className={cn(buttonVariants({ variant: "ghost", size: "sm" }), "rounded-xl")}
          >
            View all
          </Link>
        </div>
        <div className="flex min-h-0 flex-1 flex-col gap-1.5 overflow-y-auto px-3 py-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
          {/* Dynamic insights */}
          {insights.map((insight) => {
            const { Icon, iconClass, bgClass } = variantStyles[insight.variant];
            return (
              <div
                key={insight.id}
                className="flex shrink-0 items-center gap-3 rounded-xl border border-border/70 bg-muted/15 px-4 py-3 dark:bg-muted/25"
              >
                <div className={cn("flex size-8 shrink-0 items-center justify-center rounded-lg", bgClass)}>
                  <Icon className={cn("size-4", iconClass)} aria-hidden />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-semibold leading-tight text-foreground">{insight.title}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">{insight.description}</p>
                </div>
                {insight.ctaHref ? (
                  <Link
                    href={insight.ctaHref}
                    className={cn(buttonVariants({ variant: "outline", size: "sm" }), "shrink-0 rounded-xl text-xs")}
                  >
                    {insight.ctaLabel}
                  </Link>
                ) : (
                  <Button variant="outline" size="sm" className="shrink-0 rounded-xl text-xs">
                    {insight.ctaLabel}
                  </Button>
                )}
              </div>
            );
          })}

          {/* Hardcoded placeholder insights */}
          {EXTRA_INSIGHTS.map((insight) => (
            <div key={insight.id} className="flex shrink-0 items-center gap-3 rounded-xl border border-border/70 bg-muted/15 px-4 py-3 dark:bg-muted/25">
              <div className={cn("flex size-8 shrink-0 items-center justify-center rounded-lg", insight.bgClass)}>
                <insight.Icon className={cn("size-4", insight.iconClass)} aria-hidden />
              </div>
              <div className="min-w-0 flex-1">
                <p className="text-sm font-semibold leading-tight text-foreground">{insight.title}</p>
                <p className="mt-0.5 text-xs text-muted-foreground">{insight.description}</p>
              </div>
              <Link
                href={insight.ctaHref}
                className={cn(buttonVariants({ variant: "outline", size: "sm" }), "shrink-0 rounded-xl text-xs")}
              >
                {insight.ctaLabel}
              </Link>
            </div>
          ))}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="flex shrink-0 flex-col rounded-2xl border border-border/70 bg-card shadow-sm">
        <div className="flex items-center gap-2 border-b border-border/70 px-4 py-1.5 sm:px-5">
          <Zap className="size-3.5 text-amber-400" aria-hidden />
          <p className="text-sm font-semibold text-foreground">Quick Actions</p>
        </div>
        <div className="px-3 py-3">
          <div className="grid grid-cols-4 gap-2">
            <Button
              variant="secondary"
              className="h-auto flex-col gap-1 rounded-xl py-2.5 text-[11px] font-medium bg-muted hover:bg-muted/100"
              onClick={() => setAddWeddingOpen(true)}
            >
              <Plus className="size-3.5" aria-hidden />
              Add Wedding
            </Button>
            <Link
              href={tasksHref}
              className={cn(buttonVariants({ variant: "secondary" }), "h-auto flex-col gap-1 rounded-xl py-2.5 text-[11px] font-medium bg-muted hover:bg-muted/70")}
            >
              <ListChecks className="size-3.5" aria-hidden />
              Add Task
            </Link>
            <Link
              href={messagesHref}
              className={cn(buttonVariants({ variant: "secondary" }), "h-auto flex-col gap-1 rounded-xl py-2.5 text-[11px] font-medium bg-muted hover:bg-muted/70")}
            >
              <MessageSquare className="size-3.5" aria-hidden />
              Message Team
            </Link>
            <Link
              href={vendorsHref}
              className={cn(buttonVariants({ variant: "secondary" }), "h-auto flex-col gap-1 rounded-xl py-2.5 text-[11px] font-medium bg-muted hover:bg-muted/70")}
            >
              <UserPlus className="size-3.5" aria-hidden />
              Add Vendor
            </Link>
          </div>
        </div>
      </div>

      <AddWeddingFlowDialog open={addWeddingOpen} onOpenChange={setAddWeddingOpen} />
    </div>
  );
}
